---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.314
    hooks:
      - id: checkov
        files: \.y(a)?ml$
        args: ["-d", "./charts/*", "--quiet", "--framework", "helm", "--compact", "--skip-path", "tests", "--skip-check", "CKV_K8S_21,CKV_K8S_40,CKV_K8S_43"]
  # - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
  #   rev: v0.0.8
  #   hooks:
  #     - id: k8svalidate
  #       files: .yaml$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
