version: '3'

tasks:
  kind-up:
    cmds:
      - kind create cluster
  kind-down:
    cmds:
      - kind delete cluster
  argo-up:
    cmds:
      - kubectl create namespace argocd
      - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  argo-down:
    cmds:
      - kubectl delete -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - kubectl delete namespace argocd
  argo-pf:
    cmds:
      - echo -n 'username:admin password:'
      - argocd admin initial-password -n argocd
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
  deploy:
    cmds:
      - kubectl apply -f ./applications/*.yaml
  delete:
    cmds:
      - kubectl delete -f ./applications/*.yaml
