version: '3'

env:
  CKV_SKIP_CHECK: CKV_K8S_21,CKV_K8S_40,CKV_K8S_43

tasks:
  kind-up:
    cmds:
      - kind create cluster
  kind-down:
    cmds:
      - kind delete cluster
  argo-up:
    cmds:
      - kubectl create namespace argocd
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm install -n argocd argocd argo/argo-cd -f values/argocd/values-local.yaml
  argo-down:
    cmds:
      - helm uninstall -n argocd argocd
      - kubectl delete namespace argocd
  argo-pf:
    cmds:
      - echo 'username is admin'
      - echo 'password is ...'
      - argocd admin initial-password -n argocd
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
  deploy:
    cmds:
      - kubectl apply -f ./applications/*.yaml
  delete:
    cmds:
      - kubectl delete -f ./applications/*.yaml
  checkov:
    cmds:
      - checkov -d ./charts/* --quiet --soft-fail --framework helm --compact --skip-path tests > out/result-checkov-charts.txt
