apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx
            env: local
  template:
    metadata:
      name: '{{ app }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tako919191/kind-k8s-test.git
        targetRevision: main
        path: 'charts/{{ app }}'
        helm:
          releaseName: '{{ env }}'
          valueFiles:
            - '../values/{{ app }}/values-{{ env }}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ app }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
