apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx
            path: charts/nginx
            targetRevision: main
          - app: mysql
            path: charts/mysql
            targetRevision: main
  template:
    metadata:
      name: '{{ app }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tako919191/kind-k8s-test.git
        targetRevision: '{{ targetRevision }}'
        path: '{{ path }}'
        helm:
          releaseName: local
          valueFiles:
            - '../../values/{{ app }}/values-local.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ app }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
